# models/schema.yml
version: 2

sources:
  - name: finance
    database: postgres
    schema: public
    tables:
      - name: prices_raw

models:
  - name: stg_prices_raw
    description: "Nettoyage et standardisation des données de prix bruts."
    columns:
      - name: symbol
        tests: [not_null]

  - name: dim_asset
    description: "Dimension des actifs boursiers."
    columns:
      - name: symbol
        tests: [unique, not_null]

  - name: dim_calendar
    description: "Dimension calendrier."
    columns:
      - name: date
        tests: [unique, not_null]

  - name: fact_prices
    description: "Faits de prix journaliers."
    columns:
      - name: symbol
        tests: [not_null]
      - name: date
        tests: [not_null]

  - name: fact_prices_enriched
    description: "Faits enrichis avec indicateurs techniques."
